name: Ninh Ly Portfolio
favicon: null
layout_spectrum: 0.25997
typography_spectrum: 0.76294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#015079'
    - '#5ba3c9'
    - '#000000'
    - '#d2d2d3'
  brandStrength: 0.5625
  lightness: 0.6894097162876278
  saturation: 0.07670288532972336
  rhythmicContrast: 0.75
purpose: []
